spring.datasource.url=jdbc:mysql://localhost:3306/studentdb
spring.datasource.username=root
spring.datasource.password=Root@123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=8080
fast2sms.api.key=kApnZr3fFzpyoK0aSvYq7vdPrwu8LeQs9wkK64gnP8mfZEObILr0hruxNpP7
